In [1]:
!pip install -U scipy==1.10.0 numpy==1.23.5

In [2]:
!pip install -U git+https://github.com/stephenhky/PyShortTextCategorization

  Cloning https://github.com/stephenhky/PyShortTextCategorization to /tmp/pip-req-build-8lpfvxd2
  Running command git clone --filter=blob:none --quiet https://github.com/stephenhky/PyShortTextCategorization /tmp/pip-req-build-8lpfvxd2
  Resolved https://github.com/stephenhky/PyShortTextCategorization to commit e183bac2a362051087e3cb9160ccd8f2ee67f315
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.4/177.4 kB 3.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 12.2 MB/s eta 0:00:00
  Created wheel for shorttext: filename=shorttext-1.6.1-cp310-cp310-linux_x86_64.whl size=724842 sha256=7da5b27f9c861d3ef8da1d8b9dfe01723eb21446217a0461ee0fabf44fd52bb6
  Stored in directory: /tmp/pip-ephem-wheel-cache-r347qzv3/wheels/84/07/3e/bb56d79459e5c3c9111c649d174481179ef9258e9559bdd72c
Successfully

In [3]:
!python -m spacy download en

⚠ As of spaCy v3.0, shortcuts like 'en' are deprecated. Please use the
full pipeline package name 'en_core_web_sm' instead.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 17.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [4]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive


In [5]:
%cd /content/drive/My Drive/ColabData

/content/drive/My Drive/ColabData


In [6]:
from nltk.corpus import PlaintextCorpusReader
corpus_root = 'MovieReviews' # Folder Name
filelists = PlaintextCorpusReader(corpus_root, '.*',encoding='latin-1')  # wildcard is read all files in the folder
filelists.fileids()  # Get the filenames

['16748.txt',
 '17108.txt',
 '17109.txt',
 '17110.txt',
 '17111.txt',
 '17116.txt',
 '17117.txt',
 '17118.txt',
 '17119.txt',
 '17139.txt',
 '17144.txt',
 '17145.txt',
 '17146.txt',
 '17147.txt',
 '17150.txt',
 '17185.txt',
 '17192.txt',
 '17219.txt',
 '17239.txt',
 '17243.txt',
 '17254.txt',
 '17255.txt',
 '17280.txt',
 '17300.txt',
 '17303.txt',
 '17341.txt',
 '17384.txt',
 '17391.txt',
 '17398.txt',
 '17399.txt',
 '17430.txt',
 '17431.txt',
 '17447.txt',
 '17457.txt',
 '17460.txt',
 '17501.txt',
 '17518.txt',
 '17532.txt',
 '17534.txt',
 '17578.txt',
 '17609.txt',
 '17610.txt',
 '17655.txt',
 '17662.txt',
 '17663.txt',
 '17695.txt',
 '17711.txt',
 '17713.txt',
 '17753.txt',
 '17757.txt',
 '17758.txt',
 '17761.txt',
 '17803.txt',
 '17811.txt',
 '17874.txt',
 '17879.txt',
 '17886.txt',
 '17896.txt',
 '17898.txt',
 '17902.txt',
 '17912.txt',
 '17933.txt',
 '17934.txt',
 '17945.txt',
 '17963.txt',
 '17971.txt',
 '17992.txt',
 '18004.txt',
 '18016.txt',
 '18032.txt',
 '18067.txt',
 '1806

In [8]:
movie = []
for fileid in filelists.fileids():
    movie.append(filelists.raw(fileid))

In [10]:
from shorttext.utils import standard_text_preprocessor_1, DocumentTermMatrix
preprocessor = standard_text_preprocessor_1()
corpus = [preprocessor(article).split(' ') for article in movie]

In [11]:
dtm = DocumentTermMatrix(corpus, docids = filelists.fileids())

In [12]:
dtm.get_token_occurences('director')

{'16748.txt': 3.0,
 '17108.txt': 3.0,
 '17109.txt': 1.0,
 '17110.txt': 2.0,
 '17111.txt': 1.0,
 '17116.txt': 1.0,
 '17117.txt': 5.0,
 '17118.txt': 1.0,
 '17119.txt': 5.0,
 '17139.txt': 1.0,
 '17144.txt': 1.0,
 '17145.txt': 2.0,
 '17146.txt': 2.0,
 '17147.txt': 1.0,
 '17150.txt': 1.0,
 '17185.txt': 3.0,
 '17192.txt': 4.0,
 '17219.txt': 1.0,
 '17239.txt': 2.0,
 '17243.txt': 1.0,
 '17254.txt': 1.0,
 '17255.txt': 1.0,
 '17280.txt': 2.0,
 '17300.txt': 2.0,
 '17303.txt': 2.0,
 '17341.txt': 1.0,
 '17384.txt': 2.0,
 '17398.txt': 1.0,
 '17399.txt': 3.0,
 '17430.txt': 2.0,
 '17431.txt': 2.0,
 '17447.txt': 1.0,
 '17457.txt': 1.0,
 '17460.txt': 2.0,
 '17501.txt': 1.0,
 '17518.txt': 1.0,
 '17534.txt': 1.0,
 '17578.txt': 1.0,
 '17609.txt': 1.0,
 '17610.txt': 1.0,
 '17655.txt': 1.0,
 '17663.txt': 1.0,
 '17695.txt': 2.0,
 '17711.txt': 1.0,
 '17713.txt': 2.0,
 '17753.txt': 1.0,
 '17757.txt': 2.0,
 '17758.txt': 2.0,
 '17761.txt': 1.0,
 '17803.txt': 1.0,
 '17811.txt': 1.0,
 '17874.txt': 2.0,
 '17879.txt'

In [13]:
import numpy as np
import math

def entropy(p):
    if sum(p) == 0:
        return 0

    p = p/sum(p)

    p = p[ p > 0 ]

    H = -sum(p*np.log2(p))

    return H

In [14]:
direct_count = list(dtm.get_token_occurences('director').values())
direct_docs = list(dtm.get_token_occurences('director').keys())

In [15]:
print(entropy(direct_count))

7.122166395775948


In [16]:
ber = filelists.fileids()[:80]
sch = filelists.fileids()[-100:]
print(len(ber))
print(len(sch))

80
100


In [ ]:
dtm.get_token_occurences('director').keys()

In [ ]:
associ_docs = list(dtm.get_token_occurences('director').keys())
associ_docs

In [22]:
ber_count = sum([1 for doc in direct_docs if doc in ber])
sch_count = sum([1 for doc in direct_docs if doc in sch])
print(ber_count)
print(sch_count)

77
85


In [24]:
array = np.reshape((ber_count,80-ber_count
                    ,sch_count,100-sch_count),(2,2))
array

array([[77,  3],
       [85, 15]])

In [25]:
np.sum(array, axis = 0)

array([162,  18])

In [27]:
entropy(np.array( [162,18]))

0.4689955935892812

In [28]:
np.sum(array, axis = 1)

array([ 80, 100])

In [31]:
entropy_class = entropy(np.sum(array, axis = 1))
entropy_class

0.9910760598382222

In [33]:
column_probs = np.sum(array, axis = 0)/180
column_probs

array([0.9, 0.1])

In [36]:
column_entropy = np.apply_along_axis(entropy, 0, array)
column_entropy

array([0.99824017, 0.65002242])

In [37]:
column_probs*column_entropy

array([0.89841615, 0.06500224])

In [39]:
conditional_entropy = sum(column_probs*column_entropy)
conditional_entropy

0.9634183936209307

In [48]:
MI_direct = entropy_class - conditional_entropy
MI_direct

0.027657666217291488

In [52]:
words = {}
for doc in corpus:
  for word in doc:
    if word not in words:
      words[word] = 1
    else:
      words[word] += 1

In [53]:
def top_ten(word):
    direct_count = list(dtm.get_token_occurences(word).values())
    direct_docs = list(dtm.get_token_occurences(word).keys())

    entropy_value = entropy(direct_count)

    ber_count = sum([1 for doc in direct_docs if doc in ber])
    sch_count = sum([1 for doc in direct_docs if doc in sch])

    array = np.reshape((ber_count,80-ber_count
                    ,sch_count,100-sch_count),(2,2))

    marginal_entropy = entropy(np.sum(array, axis=1))

    column_prob = np.sum(array, axis=0)/180

    column_entropy = np.apply_along_axis(entropy, 0, array)

    conditional_entropy = sum(column_prob * column_entropy)

    mi = marginal_entropy - conditional_entropy
    return mi

scores = {}
for word in words.keys():
  score = top_ten(word)
  scores[word] = score

sorted_words = sorted(scores.items(), key=lambda x: x[1], reverse=True)[:10]

for word, scores in sorted_words[:10]:
    print(f"{word}: {scores}")




reserv: 0.5360547127375266
denni: 0.5177766824991015
schwartz
: 0.49202296056300543
right: 0.34124798879941887
there: 0.29684962309392304
howev: 0.27421790253727896
releas: 0.2702108404097968
cast: 0.2564686677667559
screenplai: 0.2564686677667559
produc: 0.23020448708340835


A word having a high mutual information with the author means that that word can be a strong predictor to the author as well as writing style.